[package]
name = "analyzer"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
syntax.path = "../syntax"
lean_string = { workspace = true }
rustc-hash = { workspace = true }
