use crate::{
    codegen::{ensure_file_contents, rustfmt},
    project_root,
};
use anyhow::Result;
use convert_case::{Case, Casing};
use proc_macro2::{Ident, Punct, Spacing};
use quote::{format_ident, quote};
use std::{collections::HashMap, fs};
use ungrammar::{Grammar, Rule, TokenData};
use xshell::Shell;

pub(crate) fn generate(sh: &Shell) -> Result<()> {
    let source = fs::read_to_string(project_root().join("crates/syntax/lico.ungram"))?;
    let grammer = source.parse()?;

    let syntax_kinds = {
        let kinds = collect_syntax_kinds(&grammer);
        let source = generate_syntax_kinds(kinds);
        rustfmt(sh, source)?
    };
    let ast_nodes = {
        let nodes = collect_ast_nodes(&grammer);
        let source = generate_ast_node(nodes);
        rustfmt(sh, source)?
    };

    fn add_header(source: &str) -> String {
        [
            "//! This file is generated by `cargo xtask syntax`, do not edit by hand.",
            source,
        ]
        .join("\n")
    }
    ensure_file_contents(
        &project_root().join("crates/syntax/src/syntax_kinds.rs"),
        &add_header(&syntax_kinds),
    )?;
    ensure_file_contents(
        &project_root().join("crates/syntax/src/ast_nodes.rs"),
        &add_header(&ast_nodes),
    )?;

    Ok(())
}

const PUNCT: &[(&str, &str)] = &[
    ("+", "plus"),
    ("-", "minus"),
    ("*", "star"),
    ("/", "slash"),
    ("%", "percent"),
    ("^", "caret"),
    ("&", "amp"),
    ("|", "pipe"),
    ("~", "tilde"),
    ("!", "bang"),
    ("=", "eq"),
    ("<", "lt"),
    (">", "gt"),
    (".", "dot"),
    ("@", "at"),
    (",", "comma"),
    (":", "colon"),
    ("_", "underscore"),
    ("(", "open_paren"),
    (")", "close_paren"),
    ("{", "open_brace"),
    ("}", "close_brace"),
    ("[", "open_bracket"),
    ("]", "close_bracket"),
    ("->", "arrow"),
    ("!=", "bang_eq"),
    ("..", "dot2"),
    ("==", "eq2"),
    ("<<", "lt2"),
    ("<=", "le"),
    (">>", "gt2"),
    (">=", "ge"),
];

struct SyntaxKindContainer {
    defaults: Box<[&'static str]>,
    literals: Box<[&'static str]>,
    keywords: Vec<String>,
    puncts: Vec<String>,
    nodes: Vec<String>,
}

fn collect_syntax_kinds(grammer: &Grammar) -> SyntaxKindContainer {
    let mut skc = SyntaxKindContainer {
        defaults: Box::new(["ERROR", "COMMENT", "WHITESPACE", "IDENT", "SHEBANG"]),
        literals: Box::new(["INT", "FLOAT", "STRING", "TRUE", "FALSE", "NIL"]),
        keywords: Vec::new(),
        puncts: Vec::new(),
        nodes: Vec::new(),
    };
    for token in grammer.tokens() {
        let data = &grammer[token];
        match data.name.as_str() {
            name if name.starts_with('$') => {
                let rest = &name[1..].to_uppercase();
                if skc.defaults.contains(&rest.as_str()) {
                    continue;
                }
                if skc.literals.contains(&rest.as_str()) {
                    continue;
                }
                panic!("Unknown special token: {}", name);
            }
            name if name.chars().all(|c| c.is_ascii_lowercase()) => {
                skc.keywords.push(name.to_case(Case::UpperSnake));
            }
            name if name.chars().all(|c| c.is_ascii_punctuation()) => {
                if let Some(&(_, pname)) = PUNCT.iter().find(|(p, _)| *p == name) {
                    skc.puncts.push(pname.to_string());
                } else {
                    panic!("Unknown punctuation: {}", name);
                }
            }
            unknown => panic!("Unknown token: {}", unknown),
        }
    }
    for node in grammer.iter() {
        let data = &grammer[node];
        skc.nodes.push(data.name.clone());
    }
    skc.keywords.sort();
    skc.puncts.sort();
    skc.nodes.sort();
    skc
}

fn generate_syntax_kinds(skc: SyntaxKindContainer) -> String {
    fn to_upper_ident(name: &str) -> Ident {
        let name = name.to_case(Case::Upper).replace(' ', "_");
        format_ident!("{}", name)
    }
    let syntax_kind_enum = {
        fn to_upper_ident_vec<S: AsRef<str>>(names: &[S]) -> Vec<Ident> {
            let iter = names.iter().map(|name| to_upper_ident(name.as_ref()));
            iter.collect::<Vec<_>>()
        }
        let defaults = to_upper_ident_vec(&skc.defaults);
        let literals = to_upper_ident_vec(&skc.literals);
        let keywords = to_upper_ident_vec(&skc.keywords);
        let puncts = to_upper_ident_vec(&skc.puncts);
        let nodes = to_upper_ident_vec(&skc.nodes);
        let size = defaults.len() + literals.len() + keywords.len() + puncts.len() + nodes.len();
        [
            quote! {
                #[allow(bad_style)]
                #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
                #[repr(u8)]
                pub enum SyntaxKind {
                    #( #defaults ),*,
                    #( #literals ),*,
                    #( #keywords ),*,
                    #( #puncts ),*,
                    #( #nodes ),*,
                }
                const fn _static_assert_size() {
                    const { assert!(size_of::<SyntaxKind>() == 1) }
                }
            },
            quote! {
                impl From<SyntaxKind> for rowan::SyntaxKind {
                    fn from(kind: SyntaxKind) -> Self {
                        Self(kind as u16)
                    }
                }
                impl From<rowan::SyntaxKind> for SyntaxKind {
                    fn from(kind: rowan::SyntaxKind) -> Self {
                        assert!(kind.0 <= #size, "bad SyntaxKind: {:?}", kind);
                        // SAFETY: Ensured by the assert above.
                        unsafe { ::core::mem::transmute(kind.0 as u8) }
                    }
                }
            },
            quote! {
                impl SyntaxKind {
                    pub fn is_literal(self) -> bool {
                        matches!(self, #( SyntaxKind::#literals )|*)
                    }
                    pub fn is_keyword(self) -> bool {
                        matches!(self, #( SyntaxKind::#keywords )|*)
                    }
                    pub fn is_punct(self) -> bool {
                        matches!(self, #( SyntaxKind::#puncts )|*)
                    }
                }
            },
        ]
        .map(|s| s.to_string())
        .join("\n")
    };
    let token_kind_fast_accsess = {
        let puncts_map = skc.puncts.iter().map(|name| {
            let item = PUNCT.iter().find_map(|(p, pname)| {
                if pname == name {
                    if "(){}[]_".contains(p) {
                        let c = p.chars().next().unwrap();
                        Some((quote! { #c }, to_upper_ident(pname)))
                    } else {
                        let cs = p.chars().map(|c| Punct::new(c, Spacing::Joint));
                        Some((quote! { #(#cs)* }, to_upper_ident(pname)))
                    }
                } else {
                    None
                }
            });
            item.unwrap()
        });
        let puncts = puncts_map.clone().map(|(p, _)| p).collect::<Vec<_>>();
        let names = puncts_map.map(|(_, name)| name).collect::<Vec<_>>();
        quote! {
            #[macro_export]
            #[doc(hidden)]
            macro_rules! __token_kind_fast_accsess {
                #((#puncts) => { $crate::SyntaxKind::#names }),*
            }
            pub use __token_kind_fast_accsess as T;
        }
        .to_string()
    };
    [syntax_kind_enum, token_kind_fast_accsess].join("\n")
}

#[derive(Debug)]
struct AstNode {
    name: String,
    data: AstNodeData,
}

#[derive(Debug)]
enum AstNodeData {
    Enum { variants: Vec<AstNodeVariant> },
    Struct { fields: Vec<AstNodeField> },
}

#[derive(Debug)]
enum AstNodeVariant {
    Token { name: String, label: String },
    Node { name: String, label: String },
}

#[derive(Debug)]
enum AstNodeField {
    Token { name: String, label: String },
    Child { name: String, label: String },
    Children { name: String, label: String },
}

fn collect_ast_nodes(grammer: &Grammar) -> Vec<AstNode> {
    let mut nodes = Vec::new();
    for node in grammer.iter() {
        let data = &grammer[node];
        // println!("{}", data.name);
        nodes.push(AstNode {
            name: data.name.clone(),
            data: rule_to_data(&data.rule, grammer),
        });
        fn rule_to_data(rule: &Rule, grammer: &Grammar) -> AstNodeData {
            return match rule {
                Rule::Labeled { label, rule } => match rule_to_data(rule, grammer) {
                    AstNodeData::Enum { variants: _ } => panic!("Too complex rule: {:#?}", rule),
                    AstNodeData::Struct { fields } => {
                        if fields.len() != 1 {
                            panic!("Too complex rule: {:#?}", rule);
                        }
                        let field = fields.into_iter().next().unwrap();
                        let label = label.clone();
                        use AstNodeField::*;
                        AstNodeData::Struct {
                            fields: vec![match field {
                                Token { name, label: _ } => Token { name, label },
                                Child { name, label: _ } => Child { name, label },
                                Children { name, label: _ } => Children { name, label },
                            }],
                        }
                    }
                },
                Rule::Node(_) => AstNodeData::Struct {
                    fields: vec![rule_to_field(rule, grammer)],
                },
                Rule::Token(_) => AstNodeData::Struct {
                    fields: vec![rule_to_field(rule, grammer)],
                },
                Rule::Seq(rules) => {
                    let mut fields = Vec::new();
                    for rule in rules {
                        fields.push(rule_to_field(rule, grammer));
                    }
                    AstNodeData::Struct { fields }
                }
                Rule::Alt(rules) => {
                    let mut variants = Vec::new();
                    for rule in rules {
                        variants.push(rule_to_variant(rule, grammer));
                    }
                    AstNodeData::Enum { variants }
                }
                Rule::Opt(rule) => rule_to_data(rule, grammer),
                Rule::Rep(rule) => {
                    let name = match rule as &Rule {
                        Rule::Node(node) => grammer[*node].name.clone(),
                        Rule::Token(token) => grammer[*token].name.clone(),
                        Rule::Seq(seq) => try_simp_seq(seq, grammer).unwrap_or_else(|| {
                            panic!("Too complex rule: {:#?}", seq);
                        }),
                        _ => panic!("Too complex rule: {:#?}", rule),
                    };
                    AstNodeData::Struct {
                        fields: vec![AstNodeField::Children {
                            name: name.clone(),
                            label: name.to_case(Case::Snake),
                        }],
                    }
                }
            };

            fn rule_to_variant(rule: &Rule, grammer: &Grammar) -> AstNodeVariant {
                match rule {
                    Rule::Labeled { label, rule } => {
                        let variant = rule_to_variant(rule, grammer);
                        use AstNodeVariant::*;
                        let label = label.clone();
                        match variant {
                            Token { name, label: _ } => Token { name, label },
                            Node { name, label: _ } => Node { name, label },
                        }
                    }
                    Rule::Node(node) => {
                        let data = &grammer[*node];
                        let name = data.name.clone();
                        let label = if name.ends_with("Stmt") || name.ends_with("Expr") {
                            name[..name.len() - 4].to_string()
                        } else {
                            name.clone()
                        };
                        AstNodeVariant::Node { name, label }
                    }
                    Rule::Token(token) => {
                        let data = &grammer[*token];
                        let name = get_token_data_name(data);
                        AstNodeVariant::Token {
                            name: name.clone(),
                            label: name.to_case(Case::UpperCamel),
                        }
                    }
                    _ => panic!("Too complex rule: {:#?}", rule),
                }
            }

            fn rule_to_field(rule: &Rule, grammer: &Grammar) -> AstNodeField {
                match rule {
                    Rule::Labeled { label, rule } => {
                        let field = rule_to_field(rule, grammer);
                        use AstNodeField::*;
                        let label = label.clone();
                        match field {
                            Token { name, label: _ } => Token { name, label },
                            Child { name, label: _ } => Child { name, label },
                            Children { name, label: _ } => Children { name, label },
                        }
                    }
                    Rule::Node(node) => {
                        let data = &grammer[*node];
                        AstNodeField::Child {
                            name: data.name.clone(),
                            label: data.name.to_case(Case::Snake),
                        }
                    }
                    Rule::Token(token) => {
                        let data = &grammer[*token];
                        AstNodeField::Token {
                            name: data.name.clone(),
                            label: format!(
                                "{}_token",
                                get_token_data_name(data).to_case(Case::Snake)
                            ),
                        }
                    }
                    Rule::Seq(rules) => {
                        let name = try_simp_seq(rules, grammer).unwrap_or_else(|| {
                            panic!("Too complex rule: {:#?}", rules);
                        });
                        AstNodeField::Children {
                            name: name.clone(),
                            label: name.to_case(Case::Snake),
                        }
                    }
                    Rule::Alt(_) => panic!("Too complex rule: {:#?}", rule),
                    Rule::Opt(rule) => rule_to_field(rule, grammer),
                    Rule::Rep(rule) => {
                        let name = match rule as &Rule {
                            Rule::Node(node) => grammer[*node].name.clone(),
                            Rule::Token(token) => grammer[*token].name.clone(),
                            Rule::Seq(seq) => try_simp_seq(seq, grammer).unwrap_or_else(|| {
                                panic!("Too complex rule: {:#?}", rule);
                            }),
                            _ => panic!("Too complex rule: {:#?}", rule),
                        };
                        AstNodeField::Children {
                            name: name.clone(),
                            label: name.to_case(Case::Snake),
                        }
                    }
                }
            }

            fn get_token_data_name(data: &TokenData) -> String {
                PUNCT
                    .iter()
                    .find_map(|(p, pname)| {
                        if *p == data.name {
                            Some(pname.to_string())
                        } else {
                            None
                        }
                    })
                    .unwrap_or_else(|| data.name.clone())
            }

            fn try_simp_seq(rules: &[Rule], grammer: &Grammar) -> Option<String> {
                let mut name = String::new();
                for mut rule in rules {
                    while let Rule::Opt(next) = rule {
                        rule = next;
                    }
                    let next = match rule {
                        Rule::Node(node) => grammer[*node].name.clone(),
                        Rule::Token(token)
                            if grammer[*token]
                                .name
                                .chars()
                                .all(|c| c.is_ascii_punctuation()) =>
                        {
                            continue;
                        }
                        Rule::Rep(rule) => match rule as &Rule {
                            Rule::Node(node) => grammer[*node].name.clone(),
                            Rule::Token(token)
                                if grammer[*token]
                                    .name
                                    .chars()
                                    .all(|c| c.is_ascii_punctuation()) =>
                            {
                                continue;
                            }
                            Rule::Seq(seq) => try_simp_seq(seq, grammer)?,
                            _ => return None,
                        },
                        _ => return None,
                    };
                    if name.is_empty() || name == next {
                        name = next;
                    } else {
                        return None;
                    }
                }
                Some(name)
            }
        }
    }
    nodes
}

fn generate_ast_node(nodes: Vec<AstNode>) -> String {
    let mut ts = Vec::new();
    for node in nodes {
        let name = format_ident!("{}", node.name);
        match node.data {
            AstNodeData::Enum { variants } => {}
            AstNodeData::Struct { fields } => {
                let mut child_count = HashMap::<String, u32>::new();
                let fields = fields.into_iter().map(|field| match field {
                    AstNodeField::Token { name, label } => {
                        let name = format_ident!("{}", name);
                        let label = format_ident!("{}", label);
                        quote! {
                            pub fn #label(&self) -> Option<SyntaxToken> {
                                support::token(AstNode::syntax(self), SyntaxKind::#name)
                            }
                        }
                    }
                    AstNodeField::Child { name, label } => {
                        // child_count.entry(name.clone())
                        let name = format_ident!("{}", name);
                        let label = format_ident!("{}", label);
                        quote! {
                            pub fn #label(&self) -> Option<#name> {
                                support::child(AstNode::syntax(self))
                            }
                        }
                    }
                    AstNodeField::Children { name, label } => {
                        let name = format_ident!("{}", name);
                        let label = format_ident!("{}", label);
                        quote! {
                            pub fn #label(&self) -> Option<#name> {
                                support::child(AstNode::syntax(self))
                            }
                        }
                    }
                });
                ts.push(quote! {
                    pub struct #name(SyntaxNode);
                    impl AstNode for #name {
                        type Language = LicoLanguage;
                        fn can_cast(kind: <Self::Language as rowan::Language>::Kind) -> bool {
                            kind == SyntaxKind::$kind
                        }
                        fn cast(node: rowan::SyntaxNode<Self::Language>) -> Option<Self> {
                            if Self::can_cast(node.kind()) {
                                Some(Self(node))
                            } else {
                                None
                            }
                        }
                        fn syntax(&self) -> &rowan::SyntaxNode<Self::Language> {
                            &self.0
                        }
                    }
                    impl #name {

                    }
                })
            }
        }
    }
    ts.into_iter()
        .map(|t| t.to_string())
        .collect::<Vec<_>>()
        .join("\n")
}
