[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.91"
colored = "3.0.0"
convert_case = "0.6.0"
ignore = "0.4.23"
proc-macro2 = "1.0.89"
quote = "1.0.37"
ungrammar = "1.16.1"
xflags = "0.3.2"
xshell = "0.2.6"
