[package]
name = "syntax"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
indexed_arena = { workspace = true }
lean_string = { workspace = true }
rowan = { workspace = true }
