name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Format check
        run: cargo fmt --all --check

      - name: Lint check
        run: |
          cargo check --workspace
          cargo clippy --workspace

  test-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Test
        run: cargo test --workspace

  test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Test
        run: cargo test --workspace --release
